import { SyllabusAnalysis, AssignmentAnalysis } from "./types";

export const mockAnalysis: SyllabusAnalysis = {
  course: {
    name: "Introduction to Computer Science",
    code: "CS 101",
    instructor: "Dr. Sarah Chen",
    semester: "Fall 2025",
    credits: 3,
    schedule: "Mon / Wed / Fri  10:00 – 11:00 AM  |  Room 204",
    officeHours: "Tue & Thu 2:00 – 4:00 PM, Office 318",
  },
  items: [
    {
      id: "a1",
      title: "Homework 1 — Variables & Data Types",
      type: "assignment",
      dueDate: "Sep 19",
      points: 50,
      priority: "low",
      completed: false,
    },
    {
      id: "q1",
      title: "Quiz 1 — Intro to Programming",
      type: "quiz",
      dueDate: "Sep 26",
      points: 20,
      priority: "medium",
      completed: false,
    },
    {
      id: "a2",
      title: "Homework 2 — Control Structures",
      type: "assignment",
      dueDate: "Oct 3",
      points: 50,
      priority: "low",
      completed: false,
    },
    {
      id: "q2",
      title: "Quiz 2 — Functions & Loops",
      type: "quiz",
      dueDate: "Oct 10",
      points: 20,
      priority: "medium",
      completed: false,
    },
    {
      id: "e1",
      title: "Midterm Exam",
      type: "exam",
      dueDate: "Oct 17",
      points: 100,
      priority: "high",
      completed: false,
    },
    {
      id: "a3",
      title: "Homework 3 — Data Structures",
      type: "assignment",
      dueDate: "Nov 7",
      points: 75,
      priority: "medium",
      completed: false,
    },
    {
      id: "p1",
      title: "Final Project — Part 1: Proposal",
      type: "project",
      dueDate: "Nov 14",
      points: 50,
      priority: "medium",
      completed: false,
    },
    {
      id: "q3",
      title: "Quiz 3 — OOP Concepts",
      type: "quiz",
      dueDate: "Nov 21",
      points: 20,
      priority: "medium",
      completed: false,
    },
    {
      id: "p2",
      title: "Final Project — Full Implementation",
      type: "project",
      dueDate: "Dec 5",
      points: 150,
      priority: "high",
      completed: false,
    },
    {
      id: "e2",
      title: "Final Exam",
      type: "exam",
      dueDate: "Dec 15",
      points: 150,
      priority: "high",
      completed: false,
    },
  ],
  studyPlan: [
    {
      id: "w1",
      weekLabel: "Week 1 — Sep 15–19",
      tasks: [
        {
          id: "t1",
          day: "Monday",
          date: "Sep 15",
          description: "Read Chapter 1: Intro to programming concepts & take notes",
          relatedItem: "Homework 1 — Variables & Data Types",
          completed: false,
        },
        {
          id: "t2",
          day: "Wednesday",
          date: "Sep 17",
          description: "Practice variable declarations and data type exercises",
          relatedItem: "Homework 1 — Variables & Data Types",
          completed: false,
        },
        {
          id: "t3",
          day: "Friday",
          date: "Sep 19",
          description: "Complete and submit Homework 1 before midnight",
          relatedItem: "Homework 1 — Variables & Data Types",
          completed: false,
        },
      ],
    },
    {
      id: "w2",
      weekLabel: "Week 2 — Sep 22–26",
      tasks: [
        {
          id: "t4",
          day: "Monday",
          date: "Sep 22",
          description: "Review Chapters 1–2 using flashcards and lecture slides",
          relatedItem: "Quiz 1 — Intro to Programming",
          completed: false,
        },
        {
          id: "t5",
          day: "Wednesday",
          date: "Sep 24",
          description: "Run through practice quiz problems and check understanding",
          relatedItem: "Quiz 1 — Intro to Programming",
          completed: false,
        },
        {
          id: "t6",
          day: "Friday",
          date: "Sep 26",
          description: "Quiz 1 in class — bring pencil. Then start reading Ch 3 (Control Structures)",
          relatedItem: "Quiz 1 — Intro to Programming",
          completed: false,
        },
      ],
    },
    {
      id: "w3",
      weekLabel: "Week 3 — Sep 29 – Oct 3",
      tasks: [
        {
          id: "t7",
          day: "Monday",
          date: "Sep 29",
          description: "Practice if/else and switch statements with short exercises",
          relatedItem: "Homework 2 — Control Structures",
          completed: false,
        },
        {
          id: "t8",
          day: "Wednesday",
          date: "Oct 1",
          description: "Work through loop exercises: for, while, do-while examples",
          relatedItem: "Homework 2 — Control Structures",
          completed: false,
        },
        {
          id: "t9",
          day: "Friday",
          date: "Oct 3",
          description: "Complete and submit Homework 2 — review edge cases before submitting",
          relatedItem: "Homework 2 — Control Structures",
          completed: false,
        },
      ],
    },
    {
      id: "w4",
      weekLabel: "Week 4 — Oct 6–10",
      tasks: [
        {
          id: "t10",
          day: "Monday",
          date: "Oct 6",
          description: "Review function definitions, parameters, and return values (Ch 4)",
          relatedItem: "Quiz 2 — Functions & Loops",
          completed: false,
        },
        {
          id: "t11",
          day: "Wednesday",
          date: "Oct 8",
          description: "Create a study sheet covering all loop + function patterns seen so far",
          relatedItem: "Quiz 2 — Functions & Loops",
          completed: false,
        },
        {
          id: "t12",
          day: "Friday",
          date: "Oct 10",
          description: "Quiz 2 in class. Afternoon: begin midterm outline (Chapters 1–4 summary)",
          relatedItem: "Quiz 2 — Functions & Loops",
          completed: false,
        },
      ],
    },
    {
      id: "w5",
      weekLabel: "Week 5 — Oct 13–17  ★ Midterm",
      tasks: [
        {
          id: "t13",
          day: "Monday",
          date: "Oct 13",
          description: "Full review session: re-do all homework problems from scratch",
          relatedItem: "Midterm Exam",
          completed: false,
        },
        {
          id: "t14",
          day: "Wednesday",
          date: "Oct 15",
          description: "Focus on weak areas — attend office hours with Dr. Chen if needed",
          relatedItem: "Midterm Exam",
          completed: false,
        },
        {
          id: "t15",
          day: "Friday",
          date: "Oct 17",
          description: "Midterm Exam in class — arrive early, bring student ID",
          relatedItem: "Midterm Exam",
          completed: false,
        },
      ],
    },
  ],
};

export const mockAssignmentAnalysis: AssignmentAnalysis = {
  title: "Research Paper — The Impact of AI on Modern Healthcare",
  dueDate: "Nov 15, 2025",
  whatProfessorWants:
    "A well-researched, 10–12 page academic paper that critically examines how artificial intelligence is transforming healthcare delivery, diagnosis accuracy, and patient outcomes. You should engage with peer-reviewed sources, present a balanced argument, and draw your own informed conclusions. The paper must demonstrate your ability to synthesize complex technical and ethical dimensions of AI in medicine.",
  deliverables: [
    "10–12 page paper (double-spaced, 12pt Times New Roman, 1\" margins)",
    "Minimum 8 peer-reviewed sources cited in APA format",
    "Abstract (150–200 words)",
    "Works Cited page (not counted toward page limit)",
    "Submitted as a PDF to the course portal by 11:59 PM",
  ],
  stepByStepPlan: [
    "Week 1: Choose a focused angle (e.g., AI in radiology, diagnostic chatbots, drug discovery) and get instructor approval if required",
    "Week 2: Gather 10–12 sources — use Google Scholar, PubMed, and your library's databases. Skim abstracts first",
    "Week 3: Read and annotate sources, group them by theme (benefits, risks, case studies, ethics)",
    "Week 4: Write a detailed outline and draft the introduction + thesis statement",
    "Week 5: Write the body sections — one section per major theme. Aim for 2–3 pages per section",
    "Week 6: Write the conclusion, draft the abstract, and compile the Works Cited page",
    "Final 2 days: Proofread, check citation formatting, export as PDF, submit",
  ],
  suggestedStructure: [
    "Abstract — 150–200 word summary of the entire paper",
    "Introduction — Context, why AI in healthcare matters, and your thesis",
    "Section 1: Current AI Applications — diagnostic imaging, NLP, predictive analytics",
    "Section 2: Benefits and Outcomes — accuracy improvements, cost reduction, accessibility",
    "Section 3: Risks and Ethical Concerns — bias, privacy, liability, over-reliance",
    "Section 4: Case Studies — 2–3 real-world examples (e.g., IBM Watson, FDA-approved AI tools)",
    "Conclusion — Synthesize findings, restate thesis, forward-looking statements",
    "Works Cited",
  ],
  commonMistakes: [
    "Writing a descriptive summary instead of a critical, argumentative paper",
    "Using non-peer-reviewed sources (news articles, Wikipedia) as primary evidence",
    "Vague thesis like 'AI is changing healthcare' — be specific about your claim",
    "Neglecting the ethical dimension — professors almost always expect it",
    "Going over the page limit without cutting fluff from transitions and redundant points",
    "Leaving citations until the end — track sources as you read to avoid formatting panic",
  ],
  rubricNotes: [
    "Thesis clarity and argumentation — 25 pts: must be specific and sustained throughout",
    "Research quality — 25 pts: peer-reviewed sources, proper integration, no over-quoting",
    "Critical analysis — 20 pts: your interpretation matters, not just summarizing sources",
    "Organization and structure — 15 pts: logical flow, clear transitions, proper sections",
    "Writing mechanics — 10 pts: grammar, spelling, sentence-level clarity",
    "APA formatting — 5 pts: in-text citations and Works Cited must be correct",
  ],
};
