import { SyllabusAnalysis, AssignmentAnalysis } from "./types";

export const mockAnalysis: SyllabusAnalysis = {
  course: {
    name: "Introduction to Computer Science",
    code: "CS 101",
    instructor: "Dr. Sarah Chen",
    semester: "Fall 2025",
    credits: 3,
    schedule: "Mon / Wed / Fri  10:00 – 11:00 AM  |  Room 204",
    officeHours: "Tue & Thu 2:00 – 4:00 PM, Office 318",
  },
  items: [
    {
      id: "a1",
      title: "Homework 1 — Variables & Data Types",
      type: "assignment",
      dueDate: "Sep 19",
      points: 50,
      priority: "low",
      completed: false,
    },
    {
      id: "q1",
      title: "Quiz 1 — Intro to Programming",
      type: "quiz",
      dueDate: "Sep 26",
      points: 20,
      priority: "medium",
      completed: false,
    },
    {
      id: "a2",
      title: "Homework 2 — Control Structures",
      type: "assignment",
      dueDate: "Oct 3",
      points: 50,
      priority: "low",
      completed: false,
    },
    {
      id: "q2",
      title: "Quiz 2 — Functions & Loops",
      type: "quiz",
      dueDate: "Oct 10",
      points: 20,
      priority: "medium",
      completed: false,
    },
    {
      id: "e1",
      title: "Midterm Exam",
      type: "exam",
      dueDate: "Oct 17",
      points: 100,
      priority: "high",
      completed: false,
    },
    {
      id: "a3",
      title: "Homework 3 — Data Structures",
      type: "assignment",
      dueDate: "Nov 7",
      points: 75,
      priority: "medium",
      completed: false,
    },
    {
      id: "p1",
      title: "Final Project — Part 1: Proposal",
      type: "project",
      dueDate: "Nov 14",
      points: 50,
      priority: "medium",
      completed: false,
    },
    {
      id: "q3",
      title: "Quiz 3 — OOP Concepts",
      type: "quiz",
      dueDate: "Nov 21",
      points: 20,
      priority: "medium",
      completed: false,
    },
    {
      id: "p2",
      title: "Final Project — Full Implementation",
      type: "project",
      dueDate: "Dec 5",
      points: 150,
      priority: "high",
      completed: false,
    },
    {
      id: "e2",
      title: "Final Exam",
      type: "exam",
      dueDate: "Dec 15",
      points: 150,
      priority: "high",
      completed: false,
    },
  ],
  weeklyTopics: [
    { week: 1, topic: "Variables, Data Types & Basic I/O", chapters: "Ch. 1–2" },
    { week: 2, topic: "Control Flow: Conditionals & Loops", chapters: "Ch. 3" },
    { week: 3, topic: "Functions & Modular Programming", chapters: "Ch. 4" },
    { week: 4, topic: "Arrays & Lists", chapters: "Ch. 5" },
    { week: 5, topic: "Midterm Review & Exam", chapters: "Ch. 1–5" },
    { week: 6, topic: "Strings & File I/O", chapters: "Ch. 6" },
    { week: 7, topic: "Intro to Object-Oriented Programming", chapters: "Ch. 7–8" },
    { week: 8, topic: "Final Project & Exam Prep", chapters: "Ch. 1–8" },
  ],
  studyPlan: [
    {
      id: "w1",
      weekLabel: "Week 1 — Sep 15–19",
      tasks: [
        {
          id: "t1",
          day: "Monday",
          date: "Sep 15",
          description: "Read Ch. 1–2: understand variable declarations, primitive types (int, float, bool, str) and type casting. Write 3 examples of each.",
          relatedItem: "Homework 1 — Variables & Data Types",
          notes: "Focus on the difference between mutable and immutable types — this is a common source of bugs in HW1.",
          estimatedMinutes: 60,
          completed: false,
        },
        {
          id: "t2",
          day: "Wednesday",
          date: "Sep 17",
          description: "Practice variable naming conventions and work through 5 type-conversion exercises. Debug a short program with type errors.",
          relatedItem: "Homework 1 — Variables & Data Types",
          notes: "Python's dynamic typing vs. statically typed languages is a key concept Dr. Chen emphasizes in class.",
          estimatedMinutes: 45,
          completed: false,
        },
        {
          id: "t3",
          day: "Friday",
          date: "Sep 19",
          description: "Complete and submit Homework 1. Review all your solutions for edge cases (zero values, negative numbers, empty strings).",
          relatedItem: "Homework 1 — Variables & Data Types",
          notes: "Double-check your type annotations if using Python 3.10+. Submit before midnight.",
          estimatedMinutes: 90,
          completed: false,
        },
      ],
    },
    {
      id: "w2",
      weekLabel: "Week 2 — Sep 22–26",
      tasks: [
        {
          id: "t4",
          day: "Monday",
          date: "Sep 22",
          description: "Review Ch. 1–2 using the lecture slides. Create a one-page cheat sheet covering data types, operators, and basic I/O functions.",
          relatedItem: "Quiz 1 — Intro to Programming",
          notes: "Quiz 1 will cover everything through Ch. 2. Flashcards for syntax rules help more than re-reading.",
          estimatedMinutes: 50,
          completed: false,
        },
        {
          id: "t5",
          day: "Wednesday",
          date: "Sep 24",
          description: "Run through 10 practice problems: variable assignment, type conversion, and simple input/output. Time yourself at 2 min per problem.",
          relatedItem: "Quiz 1 — Intro to Programming",
          notes: "Quizzes are closed-book, 20 minutes. Speed matters — practice writing correct syntax without autocomplete.",
          estimatedMinutes: 40,
          completed: false,
        },
        {
          id: "t6",
          day: "Friday",
          date: "Sep 26",
          description: "Quiz 1 in class. Afterward, read Ch. 3 intro on conditional logic and write 3 if/elif/else blocks from scratch.",
          relatedItem: "Quiz 1 — Intro to Programming",
          notes: "If you finish the quiz early, review your answers for off-by-one errors in any loops you wrote.",
          estimatedMinutes: 45,
          completed: false,
        },
      ],
    },
    {
      id: "w3",
      weekLabel: "Week 3 — Sep 29 – Oct 3",
      tasks: [
        {
          id: "t7",
          day: "Monday",
          date: "Sep 29",
          description: "Study Ch. 3 control flow: write examples of if/elif/else, nested conditionals, and short-circuit evaluation. Trace through 3 programs by hand.",
          relatedItem: "Homework 2 — Control Structures",
          notes: "Hand-tracing code (writing out variable values step by step) is the best way to catch logic bugs before submitting.",
          estimatedMinutes: 55,
          completed: false,
        },
        {
          id: "t8",
          day: "Wednesday",
          date: "Oct 1",
          description: "Practice all three loop types: for, while, and do-while. Write a program that uses nested loops to print a multiplication table.",
          relatedItem: "Homework 2 — Control Structures",
          notes: "Common mistake: forgetting to update the loop counter in while loops. Always check your exit condition.",
          estimatedMinutes: 60,
          completed: false,
        },
        {
          id: "t9",
          day: "Friday",
          date: "Oct 3",
          description: "Complete and submit Homework 2. Test each function with at least 3 edge cases (empty input, max value, typical input).",
          relatedItem: "Homework 2 — Control Structures",
          notes: "HW2 often has a tricky string-iteration problem — read the spec carefully before writing any code.",
          estimatedMinutes: 90,
          completed: false,
        },
      ],
    },
    {
      id: "w4",
      weekLabel: "Week 4 — Oct 6–10",
      tasks: [
        {
          id: "t10",
          day: "Monday",
          date: "Oct 6",
          description: "Read Ch. 4 on functions: parameters, return values, scope, and default arguments. Write 5 functions that each solve a different small problem.",
          relatedItem: "Quiz 2 — Functions & Loops",
          notes: "Understand the difference between global vs. local scope — Dr. Chen has tested this on every quiz so far.",
          estimatedMinutes: 60,
          completed: false,
        },
        {
          id: "t11",
          day: "Wednesday",
          date: "Oct 8",
          description: "Create a comprehensive study sheet: cover all loop patterns (accumulator, sentinel, counter) and function signatures. Test yourself without looking at notes.",
          relatedItem: "Quiz 2 — Functions & Loops",
          notes: "Combine loops + functions in practice problems — Quiz 2 always has at least one question requiring both.",
          estimatedMinutes: 50,
          completed: false,
        },
        {
          id: "t12",
          day: "Friday",
          date: "Oct 10",
          description: "Quiz 2 in class. Afternoon: start midterm review by listing all topics from Ch. 1–4 and marking your weakest areas.",
          relatedItem: "Quiz 2 — Functions & Loops",
          notes: "After the quiz, write down any questions you weren't sure about while they're fresh. Address them before the midterm.",
          estimatedMinutes: 60,
          completed: false,
        },
      ],
    },
    {
      id: "w5",
      weekLabel: "Week 5 — Oct 13–17  ★ Midterm",
      tasks: [
        {
          id: "t13",
          day: "Monday",
          date: "Oct 13",
          description: "Full midterm review: redo all homework problems from scratch without looking at your solutions. Identify and fix any mistakes.",
          relatedItem: "Midterm Exam",
          notes: "Redoing problems from scratch (not just reviewing) is proven to be 3× more effective for retention.",
          estimatedMinutes: 120,
          completed: false,
        },
        {
          id: "t14",
          day: "Wednesday",
          date: "Oct 15",
          description: "Focus on weak areas identified Monday. Attend office hours with Dr. Chen (Tue/Thu 2–4 PM) if possible. Work through 5 additional practice problems.",
          relatedItem: "Midterm Exam",
          notes: "Office hours before exams are usually small — go with 2–3 specific questions you can't resolve on your own.",
          estimatedMinutes: 90,
          completed: false,
        },
        {
          id: "t15",
          day: "Friday",
          date: "Oct 17",
          description: "Midterm Exam in class. Arrive 10 minutes early. Bring pencil, eraser, and student ID. Skim all questions before starting.",
          relatedItem: "Midterm Exam",
          notes: "Do the easiest questions first to build confidence and bank time. Leave harder ones for last.",
          estimatedMinutes: 60,
          completed: false,
        },
      ],
    },
  ],
};

export const mockAssignmentAnalysis: AssignmentAnalysis = {
  title: "Research Paper — The Impact of AI on Modern Healthcare",
  dueDate: "Nov 15, 2025",
  whatProfessorWants:
    "A well-researched, 10–12 page academic paper that critically examines how artificial intelligence is transforming healthcare delivery, diagnosis accuracy, and patient outcomes. You should engage with peer-reviewed sources, present a balanced argument, and draw your own informed conclusions. The paper must demonstrate your ability to synthesize complex technical and ethical dimensions of AI in medicine.",
  deliverables: [
    "10–12 page paper (double-spaced, 12pt Times New Roman, 1\" margins)",
    "Minimum 8 peer-reviewed sources cited in APA format",
    "Abstract (150–200 words)",
    "Works Cited page (not counted toward page limit)",
    "Submitted as a PDF to the course portal by 11:59 PM",
  ],
  stepByStepPlan: [
    "Week 1: Choose a focused angle (e.g., AI in radiology, diagnostic chatbots, drug discovery) and get instructor approval if required",
    "Week 2: Gather 10–12 sources — use Google Scholar, PubMed, and your library's databases. Skim abstracts first",
    "Week 3: Read and annotate sources, group them by theme (benefits, risks, case studies, ethics)",
    "Week 4: Write a detailed outline and draft the introduction + thesis statement",
    "Week 5: Write the body sections — one section per major theme. Aim for 2–3 pages per section",
    "Week 6: Write the conclusion, draft the abstract, and compile the Works Cited page",
    "Final 2 days: Proofread, check citation formatting, export as PDF, submit",
  ],
  suggestedStructure: [
    "Abstract — 150–200 word summary of the entire paper",
    "Introduction — Context, why AI in healthcare matters, and your thesis",
    "Section 1: Current AI Applications — diagnostic imaging, NLP, predictive analytics",
    "Section 2: Benefits and Outcomes — accuracy improvements, cost reduction, accessibility",
    "Section 3: Risks and Ethical Concerns — bias, privacy, liability, over-reliance",
    "Section 4: Case Studies — 2–3 real-world examples (e.g., IBM Watson, FDA-approved AI tools)",
    "Conclusion — Synthesize findings, restate thesis, forward-looking statements",
    "Works Cited",
  ],
  commonMistakes: [
    "Writing a descriptive summary instead of a critical, argumentative paper",
    "Using non-peer-reviewed sources (news articles, Wikipedia) as primary evidence",
    "Vague thesis like 'AI is changing healthcare' — be specific about your claim",
    "Neglecting the ethical dimension — professors almost always expect it",
    "Going over the page limit without cutting fluff from transitions and redundant points",
    "Leaving citations until the end — track sources as you read to avoid formatting panic",
  ],
  rubricNotes: [
    "Thesis clarity and argumentation — 25 pts: must be specific and sustained throughout",
    "Research quality — 25 pts: peer-reviewed sources, proper integration, no over-quoting",
    "Critical analysis — 20 pts: your interpretation matters, not just summarizing sources",
    "Organization and structure — 15 pts: logical flow, clear transitions, proper sections",
    "Writing mechanics — 10 pts: grammar, spelling, sentence-level clarity",
    "APA formatting — 5 pts: in-text citations and Works Cited must be correct",
  ],
};
